modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bountiful"
mandatory=true
versionRange="[6.0.4,7.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cozycrazyzones"
mandatory=true
versionRange="[0.3.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="conversations"
mandatory=false
versionRange="[1.0.5,)"
ordering="AFTER"
side="BOTH"
